class Buildng{
    constructor(game,layer,speed){
        this.game=game
        this.x=0;
        this.y=0;
        this.speed=speed
        this.vx=0;
        this.vy=0;
        this.image=layer;
        this.width=this.image.width;
        this.height=this.image.height;
    }
    draw(){
        this.game.ctx.drawImage(this.image,
            this.x,
            this.y,
            this.width,
            this.height,
            0,
            0,
            this.width,
            this.game.canvas.height)
        this.game.ctx.drawImage(this.image,
            this.x-this.width,
            this.y,
            this.width,
            this.height,
            0,
            0,
            this.width,
            this.game.canvas.height)
    }
    update(){
        this.x+=(this.speed*Game.speed);
        this.y+=this.vy;
        if(this.x>this.width) this.x = 0
    }
}