export class Building{
    constructor(game,image,speed){
        this.game=game
        this.image=image
        this.speed=speed
        this.width=this.image.width
        this.height=this.image.height
        this.x=0
        this.x2=-this.image.width
    }
    draw(ctx){
        ctx.drawImage(this.image,
            this.x,
            0,
            this.width,
            this.height,
            0,
            0,
            this.width,
            this.game.height)
        ctx.drawImage(this.image,
            this.x2,
            0,
            this.width,
            this.height,
            0,
            0,
            this.width,
            this.game.height)
    }
    update(){
        this.x+=this.speed*this.game.speed
        this.x2+=this.speed*this.game.speed
        if(this.x>=this.width)this.x=0
        if(this.x2>=0)this.x2=-this.image.width
    }
}